image: python:3.8

stages:
  - build

build-windows:
  stage: build
  script:
    - pip install -r requirements.txt
    - pyinstaller --onefile tcpprint.py
  artifacts:
    paths:
      - dist/tcpprint.exe
    expire_in: 30 days
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == "main"